### ISSUE TITLE
Indent code blocks

### ISSUE THREAD

**Issue by Lysxia** [plclub/plclub-web#28]
Code blocks with syntax highlighting (`pre.sourceCode`) are currently set to `margin: 0` by `pygments.css`. I think code blocks look better indented, which is why I added a `margin: 1em` to `pre`, but it only fires for raw code blocks, while the `pygments.css` rule overrides it for highlighted code blocks.

For consistency, either:

- Also indent `pre.sourceCode` blocks (but I don't know the right way to override `pygments.css`)
- Remove the `pre` rule from `css/style.css`

**Comment by dunnl** [comment]
Indentation makes sense to me. Turns out the margin is hardcoded in Skylighting [here](https://github.com/jgm/skylighting/blob/50a84b76c940ff298c82429aac45115e7f9dd4e0/skylighting-core/src/Skylighting/Format/HTML.hs). Yikes. Their code suggests their purpose is to "collapse neighbors correctly," I'm _guessing_ this has something to do with CSS top+bottom margin collapsing which would mean we can set left margins without breaking whatever they mean.

We could ask them to make this more flexible or come up with a hack, not really sure. My sense is CSS overrides are super fragile. (Tagging @euisuny if interested---how do we override someone's CSS?)
