### ISSUE TITLE
Rename "master" to "main"

### ISSUE THREAD

**Issue by hgoldstein95** [plclub/plclub-web#33]
When we get around to it, it might be a good idea to rename the master branch to "main", "canon", or anything else.

**Comment by dunnl** [comment]
I am on board with this, but I'll let it simmer for a while to let other people speak up if they want to. But do consider

1. We are a small project (so this is a straightforward change)
2. It is plausible git's `master` terminology is explicitly derived from the master/slave usage ([see here](https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html)) which the broader CS community seems to have moved away from
3. _Ce qu'on ne voit pas_. Just because the terminology does not affect you does not mean it affect other students, and our community is not sufficiently diverse that we can expect such students to speak up if they are not present in the first place
4. Students might not feel comfortable expressing their discomfort, especially if they think they'll be belittled over it.

And while I am not in a position to declare this a "small" change in terms of impact, I am in a position to declare it a small change in terms of managing a git repository.

**Comment by dunnl** [comment]
Changed to main. If anyone has any trouble updating their forks/tracking branches/misc just ping me.
